source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Tulapps/Specs.git'

use_frameworks!
target 'DoneThisKit_Tests' do
  pod 'DoneThisKit', :path => '../'
  
  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'Mockingjay', '~> 1.2.1'
end
