osx_image: xcode7.3
language: objective-c
notifications:
  email: false
before_install:
- gem install bundler
- bundle install
- bundle exec pod repo add carambalabs https://github.com/carambalabs/Specs
- bundle exec pod repo update --silent
- git remote set-url origin "https://${GITHUB_TOKEN}@github.com/carambalabs/DoneThisKit.git"
script:
- bundle exec fastlane travis
after_success:
- bundle exec fastlane push
after_success:
  - bash <(curl -s https://codecov.io/bash)

