osx_image: xcode7.3
language: objective-c
before_install:
- gem install bundler
- bundle install
- bundle exec pod repo add tulapps https://github.com/tulapps/Specs
script:
- bundle exec fastlane travis
after_success:
- bundle exec fastlane push

