osx_image: xcode7.3
language: objective-c
before_install:
- gem install bundler
- bundle install
- bundle exec pod repo add tulapps https://github.com/tulapps/Specs
- bundle exec pod repo update
- bundle exec pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/DoneThisKit.xcworkspace -scheme DoneThisKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
