before_all do
  ensure_git_status_clean
end

lane :pods do
  cocoapods(podfile: "Example/")
end

lane :tests do
  scan(workspace: "Example/DoneThisKit.xcworkspace", scheme: "DoneThisKit-Example", clean: true)
end

lane :travis do
  pods
  tests
end

lane :push do
  ensure_git_branch
  if is_ci?
    version = version_bump_podspec(path: "DoneThisKit.podspec", bump_type: "patch")
    changelog = changelog_from_git_commits
    github_release = set_github_release(
      repository_name: "tulapps/",
      api_token: ENV['GITHUB_TOKEN'],
      name: version,
      tag_name: version,
      description: changelog,
      commitish: "master"
    )
    push_to_git_remote
    pod_push(path: 'DoneThisKit.podspec', repo: 'tulapps', sources: ['https://github.com/tulapps/Specs', 'https://github.com/CocoaPods/Specs'])
  end
end